### ISSUE TITLE
Create Environment Setup Documentation

### ISSUE THREAD

**Issue by jmiller859** [abladow/BAD-USB#12]
Regardless of the type of project you are working on, you will need some work environments. You should determine tooling needs, document their usage/installation/configuration and include that information in your project repository.

Include your setup instructions in your main repository-level README.md file. The instructions should provide a clear pathway to setting up and configuring needed tools to begin working on your project. For maker-based projects this might be software dependencies and coding libraries or establishing some build files.

**Comment by twistednoble** [comment]
Completed. Not very complex tooling required.
