### ISSUE TITLE
Project Realization Report

### ISSUE THREAD

**Issue by jmiller859** [abladow/BAD-USB#13]
The bulk of the project work is centered on realizing the methodology you defined in Milestone 1. Here, you should identify the tasks you have achieved, document the product or other intellectual/applied outcomes that have resulted from your efforts, and bind your tasks to the outcomes and documentation you have produced so far.

See report outline [here.](https://github.com/MLHale/CYBR8950/blob/master/projects/milestone2.md#project-realization)

**Comment by Shmuel90** [comment]
Created and updated with our progress, hindrances, and risks to this point.
