### ISSUE TITLE
Research Paper Draft

### ISSUE THREAD

**Issue by jmiller859** [abladow/BAD-USB#14]
- Contains a well-written 500 word or less abstract that previews the argument to be made in the paper.
- Has defined section headings for each of the sections you expect to have in your paper
- Has a bulleted list of talking points you expect to fall within each section
- Section headings and bullets build a narrative flow that is compatible with your main research argument.

**Comment by Shmuel90** [comment]
Created and added to repo

**Comment by Shmuel90** [comment]
Edited based on feedback of Dr.Hale
