### ISSUE TITLE
Test device detection

### ISSUE THREAD

**Issue by jmiller859** [abladow/BAD-USB#27]
Test the effectiveness of plugging in a new keyboard while running our program multiple times with multiple devices to ensure good coverage

Test the effectiveness of plugging in a bad USB device while running our program multiple times to ensure good coverage

Update - using the event based detection we are able to detect any and all PNP devices we have had access to test with including multiple hot plug attack options.

**Comment by twistednoble** [comment]
Mitchell has gotten detection functioning for Linux
